version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./drupal:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}